<?php
namespace Database\Seeders;

use App\Models\TestCase;
use Illuminate\Database\Seeder;

class TestCaseSeeder extends Seeder
{
    public function run(): void
    {
        $testCases = [
            // Authentication Tests
            [
                'project_id' => 1,
                'test_suite_id' => 1,
                'title' => 'User can login with valid credentials',
                'description' => 'Verify that users can successfully log in with correct email and password',
                'preconditions' => 'User account exists in the system',
                'steps' => [
                    ['action' => 'Navigate to login page', 'expected' => 'Login form is displayed'],
                    ['action' => 'Enter valid email address', 'expected' => 'Email field accepts input'],
                    ['action' => 'Enter valid password', 'expected' => 'Password field accepts input'],
                    ['action' => 'Click Login button', 'expected' => 'Login is processed'],
                ],
                'expected_result' => 'User is redirected to dashboard and sees welcome message',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 5,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 1,
                'title' => 'User cannot login with invalid password',
                'description' => 'Verify that login fails with incorrect password',
                'preconditions' => 'User account exists in the system',
                'steps' => [
                    ['action' => 'Navigate to login page', 'expected' => 'Login form is displayed'],
                    ['action' => 'Enter valid email', 'expected' => 'Email accepted'],
                    ['action' => 'Enter incorrect password', 'expected' => 'Password accepted'],
                    ['action' => 'Click Login button', 'expected' => 'Login attempt processed'],
                ],
                'expected_result' => 'Error message displayed: Invalid credentials',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 5,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 1,
                'title' => 'User can register new account',
                'description' => 'Verify successful user registration',
                'preconditions' => 'Email address not already registered',
                'steps' => [
                    ['action' => 'Navigate to registration page', 'expected' => 'Registration form displayed'],
                    ['action' => 'Fill in all required fields', 'expected' => 'All fields accept input'],
                    ['action' => 'Click Register button', 'expected' => 'Registration processed'],
                ],
                'expected_result' => 'Account created successfully, user logged in',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'partial',
                'created_by' => 1,
                'estimated_time' => 10,
            ],
            
            // Product Management Tests
            [
                'project_id' => 1,
                'test_suite_id' => 2,
                'title' => 'User can search for products',
                'description' => 'Verify product search functionality',
                'preconditions' => 'Products exist in database',
                'steps' => [
                    ['action' => 'Navigate to products page', 'expected' => 'Product listing displayed'],
                    ['action' => 'Enter search term', 'expected' => 'Search field accepts input'],
                    ['action' => 'Click Search button', 'expected' => 'Search executed'],
                ],
                'expected_result' => 'Relevant products displayed in results',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 8,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 2,
                'title' => 'User can filter products by category',
                'description' => 'Verify category filtering works correctly',
                'preconditions' => 'Multiple product categories exist',
                'steps' => [
                    ['action' => 'Navigate to products page', 'expected' => 'All products shown'],
                    ['action' => 'Select a category filter', 'expected' => 'Filter applied'],
                ],
                'expected_result' => 'Only products from selected category are displayed',
                'priority' => 'medium',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 6,
            ],
            
            // Shopping Cart Tests
            [
                'project_id' => 1,
                'test_suite_id' => 3,
                'title' => 'User can add product to cart',
                'description' => 'Verify adding products to shopping cart',
                'preconditions' => 'User is logged in, products available',
                'steps' => [
                    ['action' => 'View product details', 'expected' => 'Product page displayed'],
                    ['action' => 'Click Add to Cart button', 'expected' => 'Item added to cart'],
                    ['action' => 'View cart', 'expected' => 'Cart page displayed'],
                ],
                'expected_result' => 'Product appears in cart with correct quantity and price',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 7,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 3,
                'title' => 'User can update cart quantity',
                'description' => 'Verify quantity updates in cart',
                'preconditions' => 'Product already in cart',
                'steps' => [
                    ['action' => 'Navigate to cart', 'expected' => 'Cart displayed'],
                    ['action' => 'Change quantity', 'expected' => 'Quantity field updated'],
                    ['action' => 'Click Update button', 'expected' => 'Cart recalculated'],
                ],
                'expected_result' => 'Cart total updated correctly',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 5,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 3,
                'title' => 'User can remove item from cart',
                'description' => 'Verify cart item removal',
                'preconditions' => 'Items in cart',
                'steps' => [
                    ['action' => 'Navigate to cart', 'expected' => 'Cart items displayed'],
                    ['action' => 'Click Remove button', 'expected' => 'Confirmation shown'],
                    ['action' => 'Confirm removal', 'expected' => 'Item removed'],
                ],
                'expected_result' => 'Item removed from cart, total updated',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 1,
                'estimated_time' => 5,
            ],
            
            // Payment Tests
            [
                'project_id' => 1,
                'test_suite_id' => 4,
                'title' => 'User can checkout with valid payment',
                'description' => 'Verify successful checkout process',
                'preconditions' => 'Items in cart, payment method configured',
                'steps' => [
                    ['action' => 'Proceed to checkout', 'expected' => 'Checkout page displayed'],
                    ['action' => 'Enter shipping details', 'expected' => 'Details accepted'],
                    ['action' => 'Enter payment information', 'expected' => 'Payment form displayed'],
                    ['action' => 'Click Place Order', 'expected' => 'Order processed'],
                ],
                'expected_result' => 'Order confirmation displayed, email sent',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'partial',
                'created_by' => 1,
                'estimated_time' => 15,
            ],
            [
                'project_id' => 1,
                'test_suite_id' => 4,
                'title' => 'Payment fails with invalid card',
                'description' => 'Verify error handling for invalid payment',
                'preconditions' => 'Items in cart',
                'steps' => [
                    ['action' => 'Proceed to checkout', 'expected' => 'Checkout displayed'],
                    ['action' => 'Enter invalid card details', 'expected' => 'Details accepted'],
                    ['action' => 'Click Place Order', 'expected' => 'Payment attempted'],
                ],
                'expected_result' => 'Error message shown, order not placed',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'no',
                'created_by' => 1,
                'estimated_time' => 10,
            ],
            
            // Mobile Banking Tests
            [
                'project_id' => 2,
                'test_suite_id' => 5,
                'title' => 'User can view account balance',
                'description' => 'Verify account balance display',
                'preconditions' => 'User logged in with active account',
                'steps' => [
                    ['action' => 'Login to app', 'expected' => 'Dashboard displayed'],
                    ['action' => 'Navigate to accounts', 'expected' => 'Account list shown'],
                    ['action' => 'Select account', 'expected' => 'Account details displayed'],
                ],
                'expected_result' => 'Current balance and recent transactions shown',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 2,
                'estimated_time' => 5,
            ],
            [
                'project_id' => 2,
                'test_suite_id' => 6,
                'title' => 'User can transfer money between accounts',
                'description' => 'Verify fund transfer functionality',
                'preconditions' => 'User has multiple accounts with sufficient balance',
                'steps' => [
                    ['action' => 'Navigate to transfer', 'expected' => 'Transfer form displayed'],
                    ['action' => 'Select source account', 'expected' => 'Account selected'],
                    ['action' => 'Select destination account', 'expected' => 'Destination set'],
                    ['action' => 'Enter amount', 'expected' => 'Amount accepted'],
                    ['action' => 'Confirm transfer', 'expected' => 'Transfer processed'],
                ],
                'expected_result' => 'Funds transferred, balances updated',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'partial',
                'created_by' => 2,
                'estimated_time' => 12,
            ],
            
            // More test cases for other projects
            [
                'project_id' => 3,
                'test_suite_id' => 8,
                'title' => 'User can schedule social media post',
                'description' => 'Verify post scheduling functionality',
                'preconditions' => 'User connected social media accounts',
                'steps' => [
                    ['action' => 'Create new post', 'expected' => 'Composer displayed'],
                    ['action' => 'Enter post content', 'expected' => 'Content accepted'],
                    ['action' => 'Select schedule time', 'expected' => 'Date picker shown'],
                    ['action' => 'Click Schedule', 'expected' => 'Post scheduled'],
                ],
                'expected_result' => 'Post added to schedule queue',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 3,
                'estimated_time' => 8,
            ],
            [
                'project_id' => 4,
                'test_suite_id' => 11,
                'title' => 'Patient can book appointment',
                'description' => 'Verify appointment booking process',
                'preconditions' => 'Patient account exists, doctors available',
                'steps' => [
                    ['action' => 'Navigate to appointments', 'expected' => 'Booking page shown'],
                    ['action' => 'Select doctor', 'expected' => 'Doctor selected'],
                    ['action' => 'Choose available slot', 'expected' => 'Slot selected'],
                    ['action' => 'Confirm booking', 'expected' => 'Booking processed'],
                ],
                'expected_result' => 'Appointment confirmed, confirmation email sent',
                'priority' => 'critical',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'no',
                'created_by' => 4,
                'estimated_time' => 10,
            ],
            [
                'project_id' => 5,
                'test_suite_id' => 12,
                'title' => 'User can update stock quantity',
                'description' => 'Verify inventory update functionality',
                'preconditions' => 'User has inventory access rights',
                'steps' => [
                    ['action' => 'Search for product', 'expected' => 'Product found'],
                    ['action' => 'Click Edit', 'expected' => 'Edit form displayed'],
                    ['action' => 'Update quantity', 'expected' => 'New value entered'],
                    ['action' => 'Save changes', 'expected' => 'Update processed'],
                ],
                'expected_result' => 'Stock quantity updated, audit log created',
                'priority' => 'high',
                'type' => 'functional',
                'status' => 'ready',
                'automated' => 'yes',
                'created_by' => 5,
                'estimated_time' => 6,
            ],
        ];

        foreach ($testCases as $caseData) {
            TestCase::create($caseData);
        }

        $this->command->info('Created 15 test cases');
    }
}
